#!/usr/bin/env python3
"""Generate a C blob containing the read-only PS2 game resources."""

from __future__ import annotations

import argparse
from pathlib import Path


def c_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--data", required=True, type=Path)
    parser.add_argument("--ini", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()

    assets: list[tuple[str, bytes]] = []
    for path in sorted(args.data.rglob("*")):
        if path.is_file():
            relative = path.relative_to(args.data).as_posix()
            assets.append((f"data/{relative}", path.read_bytes()))
    assets.append(("SDLPoP.ini", args.ini.read_bytes()))
    assets.sort(key=lambda item: item[0])

    blob = bytearray()
    entries: list[tuple[str, int, int]] = []
    for name, contents in assets:
        offset = len(blob)
        blob.extend(contents)
        entries.append((name, offset, len(contents)))

    args.output.parent.mkdir(parents=True, exist_ok=True)
    with args.output.open("w", encoding="utf-8", newline="\n") as out:
        out.write("/* Generated by ps2/generate_embedded_assets.py. */\n")
        out.write('#include "ps2_embedded_assets.h"\n\n')
        out.write("const unsigned char ps2_embedded_asset_blob[] = {\n")
        for index in range(0, len(blob), 16):
            chunk = blob[index:index + 16]
            out.write("    " + ", ".join(f"0x{value:02x}" for value in chunk) + ",\n")
        out.write("};\n\n")
        out.write("const ps2_embedded_asset_entry ps2_embedded_asset_entries[] = {\n")
        for name, offset, size in entries:
            out.write(f"    {{{c_string(name)}, {offset}u, {size}u}},\n")
        out.write("};\n\n")
        out.write(
            "const size_t ps2_embedded_asset_count = "
            "sizeof(ps2_embedded_asset_entries) / sizeof(ps2_embedded_asset_entries[0]);\n"
        )
        out.write(f"const size_t ps2_embedded_asset_blob_size = {len(blob)}u;\n")


if __name__ == "__main__":
    main()
