if(NOT DEFINED SDL_PS2_AUDIO_SOURCE)
    message(FATAL_ERROR "SDL_PS2_AUDIO_SOURCE is required")
endif()

file(READ "${SDL_PS2_AUDIO_SOURCE}" SDL_PS2_AUDIO_CONTENT)
set(SDL_PS2_AUDIO_OLD "this->spec.samples = 512;")
set(SDL_PS2_AUDIO_NEW "this->spec.samples = 2048;")
string(FIND "${SDL_PS2_AUDIO_CONTENT}" "${SDL_PS2_AUDIO_OLD}" SDL_PS2_AUDIO_POSITION)

if(SDL_PS2_AUDIO_POSITION EQUAL -1)
    message(FATAL_ERROR "Expected SDL2 PS2 audio buffer setting was not found")
endif()

string(REPLACE
    "${SDL_PS2_AUDIO_OLD}"
    "${SDL_PS2_AUDIO_NEW}"
    SDL_PS2_AUDIO_CONTENT
    "${SDL_PS2_AUDIO_CONTENT}"
)
file(WRITE "${SDL_PS2_AUDIO_SOURCE}" "${SDL_PS2_AUDIO_CONTENT}")
